### ISSUE TITLE
Error with reading gene annotation file 

### ISSUE THREAD

**Issue by sparthib** [OliverVoogd/FLAMES#37] opened 2024-06-27 13:56 UTC
Hi, in my code below, after `genome alignment` is completed, I get this error: 

```
[1] "completed genome alignment"
12:35:32 AM Thu Jun 27 2024 find_isoform
#### Reading Gene Annotations
Error: unordered_map::at
Execution halted
```
I am not sure if it's an issue with my gtf file. It is uncompressed. Any help would be appreciated. Thanks!

```
config_dir <- file.path(outdir, "config")
config_file <- FLAMES::create_config(config_dir, type = "sc_3end",
                                     do_barcode_demultiplex = FALSE,
                                     min_sup_cnt = 5,
                                     threads = 20)

#run minimap2

if (!any(is.na(sys_which(c("minimap2", "k8"))))) {

  config <- jsonlite::fromJSON(config_file)
  genome_bam <- rownames(minimap2_align(
    config = config, fa_file = genome_fa, fq_in = fastq, annot = annot,
    outdir = outdir
  ))
  print("completed genome alignment")
  
  find_isoform(
    annotation = annot, genome_fa = genome_fa,
    genome_bam = genome_bam, outdir = outdir, config = config
  )
  print("completed isoform identification")
  minimap2_realign(
    config = config, fq_in = fastq,
    outdir = outdir
  )
  print("created minimap2 realigned bam")
  quantify_transcript(annotation = annot, outdir = outdir, config = config)
  print("completed transcript quantification")
  sce <- create_sce_from_dir(outdir = outdir, annotation = annot)
  print("created SingleCellExperiment object")
  
}
```

**Comment by maxim-h** [comment] 2024-07-11 13:59
I experience the same problem. 

The annotation GFF file is that same as the one I've used successfully before with [LuyiTian/FLAMES](https://github.com/LuyiTian/FLAMES).

**Comment by ChangqingW** [comment] 2024-07-12 05:45
This is an issue with the C++ implementation of isoform discovery part, setting  `"multithread_isoform_identification": [false]` should be able to resolve this

**Comment by ChangqingW** [comment] 2024-07-12 05:47
duplicate of #31

**Closed as completed by ChangqingW** 2024-07-12 05:47 UTC
